apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solar-app-tls
  namespace: default
spec:
  secretName: solar-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.solar.epresanjuan.gob.ar
  dnsNames:
  - app.solar.epresanjuan.gob.ar
